// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwpMZz33zSrGy1yE51Ddqej1gvVVi3fY',
    appId: '1:344717597676:web:bf1bc3ba0c3c6821f43ec9',
    messagingSenderId: '344717597676',
    projectId: 'clubhub-a4d77',
    authDomain: 'clubhub-a4d77.firebaseapp.com',
    storageBucket: 'clubhub-a4d77.firebasestorage.app',
    measurementId: 'G-ZZGJR56X43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEH7V91iwbLZWZ3oNoFfS8SUDUph0HIM',
    appId: '1:344717597676:android:ba0bf50ffe04b420f43ec9',
    messagingSenderId: '344717597676',
    projectId: 'clubhub-a4d77',
    storageBucket: 'clubhub-a4d77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD93XIN61_vdKXoN_uDde9JfygzPOuwLUs',
    appId: '1:344717597676:ios:2caff1f281918832f43ec9',
    messagingSenderId: '344717597676',
    projectId: 'clubhub-a4d77',
    storageBucket: 'clubhub-a4d77.firebasestorage.app',
    iosBundleId: 'com.example.cuetclubhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD93XIN61_vdKXoN_uDde9JfygzPOuwLUs',
    appId: '1:344717597676:ios:2caff1f281918832f43ec9',
    messagingSenderId: '344717597676',
    projectId: 'clubhub-a4d77',
    storageBucket: 'clubhub-a4d77.firebasestorage.app',
    iosBundleId: 'com.example.cuetclubhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHwpMZz33zSrGy1yE51Ddqej1gvVVi3fY',
    appId: '1:344717597676:web:767762859bcb35dbf43ec9',
    messagingSenderId: '344717597676',
    projectId: 'clubhub-a4d77',
    authDomain: 'clubhub-a4d77.firebaseapp.com',
    storageBucket: 'clubhub-a4d77.firebasestorage.app',
    measurementId: 'G-H3FD2VSH52',
  );
}
